using System;
using System.Collections.Generic;

#nullable disable

namespace DAL.Models
{
    public partial class Accsy
    {
        public byte Nooflevel { get; set; }
        public bool Level1 { get; set; }
        public bool? Level2 { get; set; }
        public bool? Level3 { get; set; }
        public bool? Level4 { get; set; }
        public bool? Level5 { get; set; }
        public bool? Level6 { get; set; }
        public bool? Level7 { get; set; }
        public bool? Level8 { get; set; }
        public bool? Level9 { get; set; }
        public bool? Level10 { get; set; }
        public bool? Level11 { get; set; }
        public byte Totlength { get; set; }
        public bool Nocostlvl { get; set; }
        public bool Costlevel1 { get; set; }
        public bool? Costlevel2 { get; set; }
        public bool? Costlevel3 { get; set; }
        public bool? Costlevel4 { get; set; }
        public byte Totcostlen { get; set; }
        public DateTime? Startdate { get; set; }
        public string Mizdate { get; set; }
        public byte? Initno { get; set; }
        public string Posttype { get; set; }
        public string Custname { get; set; }
        public string Sepexist { get; set; }
        public string Currnexist { get; set; }
        public string Costcheck { get; set; }
        public decimal? Opgoodsbal { get; set; }
        public decimal? Cugoodsbal { get; set; }
        public decimal? Arbahvalue { get; set; }
        public string Prvarbah { get; set; }
        public string Taxdir { get; set; }
        public byte? Cuyear { get; set; }
        public string Taxmodule { get; set; }
        public string Lcmodule { get; set; }
        public string Govyear { get; set; }
        public string Consoldate { get; set; }
        public DateTime? Begindate { get; set; }
        public DateTime? Enddate { get; set; }
        public string Lcpath { get; set; }
        public string Mainglpath { get; set; }
        public string Sysname { get; set; }
        public string Indrctcode { get; set; }
        public string Rlang { get; set; }
        public bool? Costlevel5 { get; set; }
        public bool RowNo { get; set; }
        public DateTime? SystemDate { get; set; }
        public decimal? MutagraValue { get; set; }
        public string ModifyCurrnRate { get; set; }
        public string AccSerialType { get; set; }
        public string DailySerialType { get; set; }
        public string CheckEnteredDate { get; set; }
        public string CheckDateType { get; set; }
        public DateTime? MaxEnteredDate { get; set; }
        public DateTime? MinEnteredDate { get; set; }
        public string AutoSysdate { get; set; }
        public string PrvyearDataPath { get; set; }
        public bool? NumDigits { get; set; }
        public string Compcode { get; set; }
        public string LatinCustname { get; set; }
        public string StrStartdate { get; set; }
        public string StrBegindate { get; set; }
        public string StrEnddate { get; set; }
        public string StrSystemDate { get; set; }
        public string StrMaxEnteredDate { get; set; }
        public string StrMinEnteredDate { get; set; }
        public string Custaddress { get; set; }
        public string Groupp { get; set; }
        public bool? Costlevel6 { get; set; }
        public bool? Costlevel7 { get; set; }
        public bool? Costlevel8 { get; set; }
        public bool? Costlevel9 { get; set; }
        public bool? SerialMonth { get; set; }
        public decimal? SheetForm { get; set; }
        public decimal? MultiCostCenter { get; set; }
        public decimal? OpenSheet { get; set; }
        public decimal? CancelPost { get; set; }
        public string TransfereValue { get; set; }
        public string TwoCurrencyRep { get; set; }
        public string SecondCurrency { get; set; }
        public string UseRecurring { get; set; }
        public decimal? SecCurrnMutagraValue { get; set; }
        public decimal? SecCurrnOpgoodsbal { get; set; }
        public decimal? SecCurrnCugoodsbal { get; set; }
        public decimal? SecCurrnArbahvalue { get; set; }
        public string ZerosSysdate { get; set; }
        public string BudgetAlert { get; set; }
        public string HelpType { get; set; }
        public string UseDailyTrns { get; set; }
        public string CostAl { get; set; }
        public string CurrDataPath { get; set; }
        public string OtherGlUser { get; set; }
        public int? Startacctrnsm { get; set; }
        public string Showentrycopy { get; set; }
        public string Savinguser { get; set; }
        public string MultiCostGoods { get; set; }
        public bool? UseProject { get; set; }
        public bool? Noprojlvl { get; set; }
        public bool? Projlevel1 { get; set; }
        public bool? Projlevel2 { get; set; }
        public bool? Projlevel3 { get; set; }
        public bool? Projlevel4 { get; set; }
        public bool? Projlevel5 { get; set; }
        public bool? Projlevel6 { get; set; }
        public bool? Projlevel7 { get; set; }
        public bool? Projlevel8 { get; set; }
        public bool? Projlevel9 { get; set; }
        public byte? Totprojlen { get; set; }
        public string UseMulticomp { get; set; }
        public string TrnsSignatures { get; set; }
        public string ShowStopManual { get; set; }
        public string ShowMultiAgent { get; set; }
        public string UseHoldingComp { get; set; }
        public string HoldingComp { get; set; }
        public string IsCostForAccount { get; set; }
        public byte? Closing { get; set; }
        public byte? Closing1 { get; set; }
        public int? Numu { get; set; }
        public string PrintAcctrnsTotal { get; set; }
        public string ShowFixedAssets { get; set; }
        public byte? CloseTime { get; set; }
        public string StUser { get; set; }
        public int? Close { get; set; }
    }
}
