import { Data } from "popper.js";
import { Result } from "./Result";
import { FromType } from "./from-type";
import { ToType } from "./to-type";
import { ToTypeDetails } from "./to-type-details";
import { FromTypeDetails } from "./from-type-details";
import { StoreTransDetails } from "./store-trans-details";

export class StoreTransMaster {
  constructor(


    public TrnsCode?: number,
    public TrnsNo?: number,         
    public TrnsDate?: Date, 
    public Rem?: string,
    public BranchId?: number,
    public Storedocnum?: number,
    public Period?: number,
    public FromStoreAllcodesId?: number,
    public ToStoreAllcodesId?: number,
    public StoreTrnsMId?: number,
    public From_Type?: FromType[],
    public To_Type?: ToType[],
    public FromTypeDetails?: FromTypeDetails[],
    public ToTypeDetails?: ToTypeDetails[],
    public Branches?: Result[],




    //public Disc?: number, 
    //public DiscRate?: number, 
    //public Stax?: number, 
    //public StaxRate?: number, 
    //public Ctax?: number, 
    //public CtaxRate?: number, 
    //public DepOnGroupno?: number, 
    
    //public Total?: number, 
    //public Currencyid?: number, 
     
    //public Salesrep?: number,     
    //public Currencyrate?: number, 
    //public Initcash?: number,     
    //public CtaxDisc?: number,     
    //public CtaxDiscRate?: number, 
    //public ExpensesAdd?: number,  
    //public ExpensesDisc?: number, 
    //public ExpensesNoeffect?: number,    
    //public Pricelistid?: number, 
    //public StartDate?: Data, 
    //public EndDate?: Date,
    //public PeriodLimit?: number,
    //public MainCostcenterid?: number,
    //public MainAccountid?: number,
    //public TransferCost?: number,
    //public Discountlistid?: number,
    //public Commited?: number,
    //public Instprogramid?: number,
    //public Tax41rate?: number,
    //public Tax41value?: number,           
    //public Netvalue?: string,
    //public Tax41trnsnatural?: string,
    //public Trnsusersid?: number,
    //public Disc2?: number,
    //public Disc2Rate?: number,
    //public Addition1?: number,
    //public Addition1Rate?: number,
    //public Addition2?: number,
    //public Addition2Rate?: number,
    //public Addition3?: number,
    //public Addition3Rate?: number,
    //public Remark1?: string,
    //public Remark1e?: string,
    //public Remark2?: string,
    //public Remark2e?: string,
    //public Remark3?: string,
    //public Remark3e?: string,
    //public Remark4?: string,
    //public Remark4e?: string,
    //public Remark5?: string,
    //public Remark5e?: string,
    //public Remark6?: string,
    //public Remark6e?: string,
    //public Batchno?: string,
    //public Numbervalue?: string,
    //public Stringvalue?: string,
    //public Productionstageid?: number,
    //public     Createitems?: string,           
    //    public Remark7?:     string ,       
    //    public Remark7e?:   string  ,      
    //    public Remark8?:     string ,       
    //    public Remark8e?:    string ,       
    //    public Remark9?:    string  ,      
    //    public Remark9e?:    string ,       
    //    public Remark10?:    string ,       
    //    public Remark10e?:   string ,       
    //    public Irrigationneed?:number, 
    //    public  Paytypespec?:  string,     
    //    public Deliveryplace?: string,     
    //public Receivedate?: Date,    
    //public Choicereason?: string,      
    //    public  Cargoexpected?: Date, 
    //    public  Cargoactually?: Date, 
    //public Portarrival?: Date,
    //public Cargopaper?: boolean,
    //public Typeid?: number,          
    //    public  Agridataid?:number,      
    //    public  Managername?:string,       
    //    public  Employeeno?:number,      
    //    public  Irrigatemachine?: string,  
    //    public  Weathercond?:string,  
    //    public  Soilcond?: string,  
    //    public  Createdby?: string,  
    //    public Updatedby?: string , 
    //    public  ExpensesCurr?:string,    
    //public ExpensesRate?: string,
    //public ExpensesNstringet?: boolean,       
    //public Shipcostringid?: number,
    //public Shiptrstringnsid?: number,
    //public Clearancecoid?: number,
    //public Shipportid?: number,
    //public Arrivalportid?: number,
    //public Shipboatid?: number,      
    //    public  Shippolino?: string,       
    //    public  Shipweekno?: string,       
    //    public  Shiplotno?:  string,      
    //    public  Customdocno?:string,       
    //public Patchno?: string,
    
  ) {}        
}
