export class TransactionSpecific {
  constructor(TrnsCode?: number,
    Aname?: string,
    Ename?: string,
    TrnsType?: number,
    TrnsNature?: number,
    SalesRep?: boolean,
    PriceEffect?: boolean,
    PayEffect?: boolean,
    QtyEffect?: boolean,
    ItemPrice?: number,
    TrnsDisc?: boolean,
    TrnsDiscRate?: number,
    ItemDisc?: boolean,
    Stax?: boolean,
    StaxRate?: number,
    Ctax?: boolean,
    CtaxRate?: number,
    ItemStax?: boolean,
    StoreItemfromsSpecsId?: number,
    FromStoreAllcodesId?: number,
    ToStoreAllcodesId?: number,
    Item2ndprice?: number,
    ShowPrice?: boolean,
    Show2ndprice?: boolean,
    Item2ndpriceEffect?: boolean,
    ItemPricelistId?: number,
    GetPricelist?: boolean,
    Shippingspecs?: boolean,
    Shippingeffectonholder?: boolean,
    TrnsnoCreation?: boolean,
    TrnsnoRepeat?: boolean,
    TrnsnoEdit?: boolean,
    DocnumCreation?: boolean,
    DocnumRepeat?: boolean,
    DocnumEdit?: boolean,
    CustmorDisc?: boolean,
    Item2nddisc?: boolean,
    Getdisclist?: boolean,
    ItemDisclistId?: number,
    Hascashpayment?: number,
    Cashid?: number,
    Financetranscode?: number,
    Multycurrency?: number,
    Needaccept?: boolean,
    Acceptcount?: number,
    Hasexpenses?: boolean,
    ExpensesEffect?: boolean,
    CtaxDisc?: boolean,
    CtaxDiscRate?: number,
    Financedistid?: number,
    MainCostCenter?: boolean,
    MainAccount?: boolean,
    DetailCostCenter?: boolean,
    DetailAccount?: boolean,
    DepositFlag?: boolean,
    AllowanceDateType?: boolean,
    HasStartDate?: boolean,
    HasEndDate?: boolean,
    ShowBal?: boolean,
    Costcentereffect?: boolean,
    CustmorCtax?: boolean,
    TransferCostType?: boolean,
    Dsttype?: number,
    Mustdsttype?: boolean,
    Dstindetails?: boolean,
    Dstdetailstype?: number,
    Transrepeatonperiod?: boolean,
    Docrepeatonperiod?: boolean,
    Usebarcode?: boolean,
    Showtax41?: boolean,
    Showlc?: boolean,
    Showdependdoc?: boolean,

    //Showcargo": tru,
    //Showtermsofpayment": true,
    //Showrequireddocument": true,
    //Showsupplyorderstatus": true,
    //Showexpchoose": false,
    //Reservation": false,
    //Hasproductiondata": false,
    //Noduplicateserial": 0,
    //Fromrequired": true,
    //Torequired": false,
    //Stage": true,
    //Createitems": false,
    //Approvedvendor": false,
    //Committeeexist": true,
    //Mobiletrans": false,
    //Weekno": false,
    //Fromtodate": false,
    //Itemapproved": true,
    //Begintime": false,
    //Endtime": false,
    //Safeperiod": false,
    //Paymenttype": true,
    //Deliveryplace": true,
    //Inttradespec": false,
    //Receivedate": true,
    //Choicereason": null,
    //Paymentspec": true,
    //Committee": 3,
    //Irrigationneed": true,
    //Pool": null,
    //Allowqtyedit": null,
    //Cargoexpected": true,
    //Cargoactually": true,
    //Cargopaper": true,
    //Portarrival": true,
    //Detentionrev": false,
    //Releasetype": false,
    //Licenseno": false,
          
          
          
    
    
    








  ) { }
}


//"TrnsCode": 1,
//"Aname": "طلب احتياجات",
// "Ename": null,
// "TrnsType": 1,
// "TrnsNature": 1,
// "SalesRep": false,
// "PriceEffect": false,
// "PayEffect": true,
// "QtyEffect": false,
// "ItemPrice": 0,
//   "TrnsDisc": true,
//     "TrnsDiscRate": 0,
//       "ItemDisc": false,
//         "Stax": true,
//           "StaxRate": 0,
//             "Ctax": true,
//               "CtaxRate": 0,
//                 "ItemStax": false,
//                   "StoreItemfromsSpecsId": null,
//                     "FromStoreAllcodesId": null,
//                       "ToStoreAllcodesId": null,
//                         "Item2ndprice": 1,
//"ShowPrice": true,
//  "Show2ndprice": false,
//    "Item2ndpriceEffect": false,
//      "ItemPricelistId": 0,
//        "GetPricelist": false,
//          "Shippingspecs": false,
//            "Shippingeffectonholder": false,
//              "TrnsnoCreation": false,
//                "TrnsnoRepeat": true,
//                  "TrnsnoEdit": true,
//                    "DocnumCreation": false,
//                    "DocnumRepeat": true,
//                    "DocnumEdit": true,
//                    "CustmorDisc": false,
//                    "Item2nddisc": false,
//                    "Getdisclist": false,
//                    "ItemDisclistId": null,
//  "Hascashpayment": 0,
//  "Cashid": null,
//  "Financetranscode": null,
//  "Multycurrency": 1,
//  "Needaccept": true,
//  "Acceptcount": null,
//  "Hasexpenses": true,
//  "ExpensesEffect": false,
//  "CtaxDisc": true,
//  "CtaxDiscRate": 0,
//  "Financedistid": 1,
//  "MainCostCenter": true,
//  "MainAccount": true,
//  "DetailCostCenter": null,
//  "DetailAccount": null,
//  "DepositFlag": false,




//  "AllowanceDateType": false,
//  "HasStartDate": true,
//  "HasEndDate": true,
//  "ShowBal": true,
//  "Costcentereffect": false,
//  "CustmorCtax": false,
//  "TransferCostType": null,
//  "Dsttype": null,
//  "Mustdsttype": null,
//  "Dstindetails": false,
//  "Dstdetailstype": null,
//  "Transrepeatonperiod": true,
//  "Docrepeatonperiod": true,
//  "Usebarcode": false,
//  "Showtax41": false,
//  "Showlc": true,
//  "Showdependdoc": true,




//"Showcargo": true,
//"Showtermsofpayment": true,
//"Showrequireddocument": true,
//"Showsupplyorderstatus": true,
//"Showexpchoose": false,
//"Reservation": false,
//"Hasproductiondata": false,
//"Noduplicateserial": 0,
//"Fromrequired": true,
//"Torequired": false,
//"Stage": true,
//"Createitems": false,
//"Approvedvendor": false,
//"Committeeexist": true,
//"Mobiletrans": false,
//"Weekno": false,
//"Fromtodate": false,
//"Itemapproved": true,
//"Begintime": false,
//"Endtime": false,
//"Safeperiod": false,
//"Paymenttype": true,
//"Deliveryplace": true,
//"Inttradespec": false,
//"Receivedate": true,
//"Choicereason": null,
//"Paymentspec": true,
//"Committee": 3,
//"Irrigationneed": true,
//"Pool": null,
//"Allowqtyedit": null,
//"Cargoexpected": true,
//"Cargoactually": true,
//"Cargopaper": true,
//"Portarrival": true,
//"Detentionrev": false,
//"Releasetype": false,
//"Licenseno": false,
//                                                                 "Licensedate": false,
//                                                                             "Agriitems": false,
//                                                                                       "Typeid": true,
//                                                                                         "Agridataid": true,
//                                                                                           "Managername": true,
//                                                                                             "Employeeno": true,
//                                                                                               "Irrigatemachine": true,
//                                                                                                 "Watervolume": false,
//                                                                                                   "Actualspace": false,
//                                                                                                     "Waterpressure": null,
//                                                                                                       "Purpose": false,
//                                                                                                         "Injureid": false,
//                                                                                                           "Phi": false,
//                                                                                                             "Workingtime": false,
//                                                                                                               "Restrictionperiod": false,
//                                                                                                                 "Requiredprocedure": false,
//                                                                                                                   "Ageid": false,
//                                                                                                                     "Agriid": null,
//                                                                                                                       "Processid": false,
//                                                                                                                         "Fertunit": false,
//                                                                                                                           "Agriqty": false,
//                                                                                                                             "Agridata": null,
//                                                                                                                               "Fromtime": false,
//                                                                                                                                 "Totime": false,
//                                                                                                                                   "Soilcond": true,
//                                                                                                                                     "Weathercond": true,
//                                                                                                                                       "Enginepressure": false,
//                                                                                                                                         "Irrigationempshow": true,
//                                                                                                                                           "Agrinorepeat": false,
//                                                                                                                                             "Taxdiscprnt": false,
//                                                                                                                                               "ExpensesCurr": true,
//                                                                                                                                                 "ExpensesRate": true,
//                                                                                                                                                   "ExpensesDist": null,
//                                                                                                                                                     "Showexptype": false,
//                                                                                                                                                       "Showprodstage": false,
//                                                                                                                                                         "Printcostprice": "0",
//                                                                                                                                                           "Showpopprice": false,
//                                                                                                                                                             "Showfarm": false,
//                                                                                                                                                               "Showagricontainer": false,
//                                                                                                                                                                 "Shipco": true,
//                                                                                                                                                                   "Shiptrns": true,
//                                                                                                                                                                     "Clearanceco": true,
//                                                                                                                                                                       "Shipport": true,
//                                                                                                                                                                         "Arrivalport": true,
//                                                                                                                                                                           "Shipboat": true,
//                                                                                                                                                                             "Shippolino": true,
//                                                                                                                                                                               "Shipweekno": true,
//                                                                                                                                                                                 "Shiplotno": true,
//                                                                                                                                                                                   "Itemclone": false,
//                                                                                                                                                                                     "Getdisclist2": false,
//                                                                                                                                                                                       "Showeditbtn": false,
//                                                                                                                                                                                         "Itempriceavg": false,
//                                                                                                                                                                                           "Freeitem": 0,
//                                                                                                                                                                                             "Pricedecpoints": 0,
//                                                                                                                                                                                               "Mustaccount": false,
//                                                                                                                                                                                                 "Mustdimension": false,
//                                                                                                                                                                                                   "Execperco": false,
//                                                                                                                                                                                                     "Prevperc": false,
//                                                                                                                                                                                                       "Customdocno": null,
//                                                                                                                                                                                                         "Customdocnoar": null,
//                                                                                                                                                                                                           "Customdocnoshow": 1,
//                                                                                                                                                                                                             "Patchno": true,
//                                                                                                                                                                                                               "Lotasdocno": false,
//                                                                                                                                                                                                                 "Hasattachments": false,
//                                                                                      "TransactionsNames": []
