export class StoreDepSpecDetails_VM {
  constructor
    (

        public GroupId?:number, 
        public  Depslot?:number,
        public  DepOnTrnsCode?:number,
        public  Getitems?:number,
        public  Depsign?:number,
        public  GetFrom?:number,
        public  GetTo?:number,
        public StoreDepSpecsDetailsId?:number,
        public  CollectItem?:number,
        public  DepType?:number,
        public  Onlyonedep?:number,
        public  DepMust?:number,
        public  Adjustdeponprice?:number,
        public  Payrevers ?:number,
        public  DepList?:number,
        public  FromFilter?:number,
        public  ToFilter?:number,
        public  Sumqtyonitems?:number,
        public  DepShipinfo?:number,
        public  DepMaincostcent?:number,
        public  Getdepocostcent?:number,
        public  Depmainacc?:number,
        public  Getdepoacc?:number,
        public  Getdesc?:number,
        public  DepPricType?:number,
        public AdditemOutDep?:number,
        public  Depquantities?:number,
        public  Autodep?:number,
        public  Autodepcode?:number,
        public  Salesrep?:number,
        public  Ctax?:number,
        public  Ctaxdisc?:number,
        public  Stax?:number,
        public  Depqtyratio?:number,
        public  Getcost? :number,
        public  Deponpricecost?:number,
        public Hasextras?: number,
        public Getdocno?: boolean,
    )
  { }
}
